# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190809_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='轮播课程'),
        ),
    ]
